require:
  - rubocop-rails
  - rubocop-rspec
  - rubocop-performance
AllCops:
  Exclude:
    - 'spec/spec_helper.rb'
    - 'spec/rails_helper.rb'
    - 'db/schema.rb'
    - 'bin/*'
Style/FrozenStringLiteralComment:
  Enabled: false
Style/SymbolArray:
  EnforcedStyle: brackets
Style/Documentation:
  Enabled: false

Metrics/MethodLength:
  Max: 15
  Exclude:
    - 'db/migrate/*'
Metrics/AbcSize:
  Enabled: false

Layout/LineLength:
  Max: 150
