require:
  - rubocop-rails
  - rubocop-rspec
  - rubocop-performance
AllCops:
  Exclude:
    - 'spec/spec_helper.rb'
    - 'spec/rails_helper.rb'
    - 'db/schema.rb'
    - 'bin/*'
Style/FrozenStringLiteralComment:
  Enabled: false
Style/SymbolArray:
  EnforcedStyle: brackets
Style/Documentation:
  Enabled: false

Metrics/MethodLength:
  Max: 15
  Exclude:
    - 'db/migrate/*'
Metrics/AbcSize:
  Enabled: false

Layout/LineLength:
  Max: 150

Rails/CreateTableWithTimestamps:
  Exclude:
    - 'db/migrate/20200114144054_rolify_create_roles.rb'
Rails/HasAndBelongsToMany:
  Exclude:
    - 'app/models/role.rb'
