require:
  - rubocop-rails
  - rubocop-rspec
  - rubocop-performance

Style/FrozenStringLiteralComment:
  Enabled: false
Style/SymbolArray:
  EnforcedStyle: brackets
Style/Documentation:
  Enabled: false

Metrics/MethodLength:
  Max: 20
Metrics/AbcSize:
  Enabled: false

Layout/LineLength:
  Max: 150

AllCops:
  Exclude:
    - 'spec/spec_helper.rb'
    - 'spec/rails_helper.rb'
    - 'db/schema.rb'
    - 'db/migrate/*'
    - 'bin/*'

